// Puja catalogue. Each puja carries an English + Hindi title/desc so the UI
// can render in either language without branching logic in the page.
// Navratri stays first during the Sharad Navratri window, then Shraadh.
export const pujas = [
  {
    id: "navratri",
    code: "PUJA-010",
    title: "Sharad Navratri Devi Puja (9 Nights of Shakti)",
    titleHi: "शारदीय नवरात्रि देवी पूजा (शक्ति की नौ रातें)",
    deity: "Durga",
    temple: "Shakti Peeth Seva · At Home",
    date: "Oct 11, 2026",
    time: "06:00 AM",
    price: 2101,
    tag: "Navratri Special",
    purpose: "Protection",
    type: "Puja",
    image: "/puja/navratra.jpg",
    desc: "Personalised Navratri recitations, from Saptashloki Durga to Chandi Path and Mantra Samputa, guided by your intention and performed with traditional vidhi.",
    descHi: "सप्तश्लोकी दुर्गा से चंदी पाठ और संपुट मंत्र तक, आपके संकल्प के अनुरूप पारंपरिक विधि से संपन्न व्यक्तिगत नवरात्रि पाठ।",
  },
  {
    id: "shraadh",
    code: "PUJA-009",
    title: "Shraadh (PITRU PAKSHA ONLINE SHRADH POOJA)",
    titleHi: "श्राद्ध (पितृ पक्ष ऑनलाइन श्राद्ध पूजा)",
    deity: "Pitru",
    temple: "At Home · Temple · Gaya Ji",
    date: "Pitru Paksha",
    time: "Per Tithi",
    price: 2101,
    tag: "Ancestral",
    purpose: "Ancestral peace",
    type: "Shraadh",
    image:
      "/puja/Shraadh.jpg",
    desc: "Ancestral observance performed with śraddhā — at home with a Vedacharya, on your behalf.",
    descHi:
      "श्रद्धा के साथ संपन्न होने वाला पितृ अनुष्ठान — घर पर वेदाचार्य के साथ, आपकी ओर से।",
  },
  {
    id: "mahadeva-rudra",
    code: "PUJA-001",
    title: "Maha Rudrabhishek",
    titleHi: "महा रुद्राभिषेक",
    deity: "Shiva",
    temple: "Kashi Vishwanath",
    date: "Sep 09, 2026",
    time: "07:30 AM",
    price: 1100,
    tag: "Evergreen",
    purpose: "Peace & protection",
    type: "Abhishek",
    image:
      "/puja/Maha Rudrabhishek.jpg",
    desc: "A traditional Rudrabhishek with a personalized Sankalp and recorded ceremony access.",
    descHi: "व्यक्तिगत संकल्प और रिकॉर्ड किए गए समारोह की पहुँच के साथ एक पारंपरिक रुद्राभिषेक।",
  },
  {
    id: "ganesha-vighna",
    code: "PUJA-002",
    title: "Ganesh Vighnaharta Puja",
    titleHi: "गणेश विघ्नहर्ता पूजा",
    deity: "Ganesh",
    temple: "Ujjain Mahakaleshwar",
    date: "Sep 10, 2026",
    time: "09:00 AM",
    price: 851,
    tag: "Popular",
    purpose: "New beginnings",
    type: "Archana",
    image:
      "/puja/Ganesh Vighnaharta Puja.jpg",
    desc: "A focused Ganesh puja for a new chapter, journey, venture or important decision.",
    descHi: "नए अध्याय, यात्रा, उद्यम या महत्वपूर्ण निर्णय के लिए एक केंद्रित गणेश पूजा।",
  },
  {
    id: "lakshmi-diwali",
    code: "PUJA-003",
    title: "Mahalakshmi Dhan Akarshan",
    titleHi: "महालक्ष्मी धन आकर्षण",
    deity: "Lakshmi",
    temple: "Lotus Temple Seva",
    date: "Nov 08, 2026",
    time: "06:15 PM",
    price: 1251,
    tag: "Festival",
    purpose: "Wealth & prosperity",
    type: "Puja",
    image:
      "/puja/Mahalakshmi Dhan Akarshan.jpg",
    desc: "An intimate Lakshmi offering for Diwali and the season of new beginnings.",
    descHi: "दीवाली और नए आरंभ के मौसम के लिए एक अंतरंग लक्ष्मी अनुष्ठान।",
  },
  {
    id: "hanuman-sankat",
    code: "PUJA-004",
    title: "Sankat Mochan Hanuman Seva",
    titleHi: "संकट मोचन हनुमान सेवा",
    deity: "Hanuman",
    temple: "Ayodhya Ram Janmabhoomi",
    date: "Sep 12, 2026",
    time: "05:45 AM",
    price: 951,
    tag: "Limited slots",
    purpose: "Peace & protection",
    type: "Seva",
    image:
      "/puja/Sankat Mochan Hanuman.jpg",
    desc: "A focused Hanuman seva for courage, steadiness and protection.",
    descHi: "साहस, स्थिरता और सुरक्षा के लिए एक केंद्रित हनुमान सेवा।",
  },
  {
    id: "satyanarayan",
    code: "PUJA-005",
    title: "Satyanarayan Katha",
    titleHi: "सत्यनारायण कथा",
    deity: "Vishnu",
    temple: "Badrinath Seva Mandal",
    date: "Sep 13, 2026",
    time: "11:00 AM",
    price: 1001,
    tag: "Evergreen",
    purpose: "Family & harmony",
    type: "Katha",
    image:
      "/puja/Satyanarayan Katha.jpg",
    desc: "A family-oriented Satyanarayan ritual with personalized Sankalp.",
    descHi: "व्यक्तिगत संकल्प के साथ परिवार-उन्मुख सत्यनारायण अनुष्ठान।",
  },
  {
    id: "navagraha",
    code: "PUJA-006",
    title: "Navagraha Shanti Homam",
    titleHi: "नवग्रह शांति होमम",
    deity: "Navagraha",
    temple: "Kanchipuram Seva",
    date: "Sep 15, 2026",
    time: "08:00 AM",
    price: 1501,
    tag: "Remedy",
    purpose: "Dosha & remedy",
    type: "Homam",
    image:
      "/puja/Navagraha Shanti Homam.jpg",
    desc: "A structured homam experience around traditional Navagraha practices.",
    descHi: "पारंपरिक नवग्रह पद्धतियों के इर्द-गिर्द एक संरचित होमम अनुभव।",
  },
  {
    id: "durga-path",
    code: "PUJA-007",
    title: "Durga Saptashati Path",
    titleHi: "दुर्गा सप्तशती पाठ",
    deity: "Durga",
    temple: "Kolkata Shakti Peeth Seva",
    date: "Oct 06, 2026",
    time: "06:30 AM",
    price: 1701,
    tag: "Navratri",
    purpose: "Protection",
    type: "Path",
    image:
      "/puja/Durga Saptashati Path.jpg",
    desc: "A Navratri path experience with family Sankalp.",
    descHi: "पारिवारिक संकल्प के साथ एक नवरात्रि पाठ अनुभव।",
  },
  {
    id: "maha-mrityunjaya",
    code: "PUJA-008",
    title: "Mahamrityunjaya Jaap",
    titleHi: "महामृत्युंजय जाप",
    deity: "Shiva",
    temple: "Somnath Temple Seva",
    date: "Sep 18, 2026",
    time: "08:15 AM",
    price: 1401,
    tag: "Evergreen",
    purpose: "Health & well-being",
    type: "Jaap",
    image:
      "/puja/Mahamrityunjaya Jaap.jpg",
    desc: "A traditional mantra jaap experience with Sankalp and post-puja video delivery.",
    descHi: "संकल्प और पूजा के बाद वीडियो डिलीवरी के साथ एक पारंपरिक मंत्र जाप अनुभव।",
  },
];
export const festivals = [
  {
    name: "Ganesh Chaturthi",
    nameHi: "गणेश चतुर्थि",
    date: "Sep 12",
    note: "Ten days of devotion",
    noteHi: "दस दिन की भक्ति",
    image:
      "/festivals/Ganesh Chaturthi.jpg",
  },
  {
    name: "Navratri",
    nameHi: "नवरात्रि",
    date: "Oct 11",
    note: "Nine nights of devotion",
    noteHi: "नौ रातों की भक्ति",
    image:
      "/festivals/Navratri.jpg",
  },
  {
    name: "Diwali",
    nameHi: "दीवाली",
    date: "Nov 8",
    note: "Light, Lakshmi, new beginnings",
    noteHi: "प्रकाश, लक्ष्मी, नए आरंभ",
    image:
      "/festivals/Diwali.jpg",
  },
  {
    name: "Mahashivratri",
    nameHi: "महाशिवरात्रि",
    date: "Feb 15",
    note: "Night of Shiva",
    noteHi: "शिव की रात",
    image:
      "/festivals/Mahashivratri.jpg",
  },
];
export const stories = [
  {
    id: "navratri-nine-nights",
    category: "Festivals",
    title: "Nine nights of Devi: how Navratri is actually observed",
    titleHi: "देवी की नौ रातें: नवरात्रि कैसे मनाई जाती है",
    read: "9 min",
    date: "Oct 02, 2026",
    image: "/puja/navratra.jpg",
    excerpt: "Kalash Sthapana to Kanya Pujan to Havan: the full Sharad Navratri sequence with dates, colours and vrat rules.",
    excerptHi: "कलश स्थापना से कन्या पूजन और हवन तक: तिथि, रंग और व्रत नियमों के साथ शारदीय नवरात्रि की पूरी विधि।",
  },
  {
    id: "why-sankalp",
    category: "Rituals / Puja Vidhi",
    title: "What a Sankalp really means, and why your name matters",
    titleHi: "संकल्प का वास्तविक अर्थ, और आपके नाम का महत्व",
    read: "6 min",
    date: "Sep 04, 2026",
    image:
      "/stories/What a Sankalp really means, and why your name matters.png",
    excerpt: "A simple guide to the intention placed at the heart of a traditional puja.",
    excerptHi: "पारंपरिक पूजा के केंद्र में रखे गए संकल्प का सरल परिचय।",
  },
  {
    id: "temple-bells",
    category: "Temple Histories",
    title: "The language of temple bells",
    titleHi: "मंदिर घंटों की भाषा",
    read: "4 min",
    date: "Aug 29, 2026",
    image:
      "/stories/The language of temple bells.png",
    excerpt: "Why bells are rung, what the ritual means, and what devotees are actually doing.",
    excerptHi:
      "घंटे क्यों बजाए जाते हैं, अनुष्ठान का क्या अर्थ है, और भक्त वास्तव में क्या कर रहे हैं।",
  },
  {
    id: "shiva-ritual",
    category: "Deity Stories",
    title: "Why Rudrabhishek is one of the most requested Shiva rituals",
    titleHi: "रुद्राभिषेक सबसे माँगे जाने वाले शिव अनुष्ठानों में से एक क्यों है",
    read: "8 min",
    date: "Aug 22, 2026",
    image:
      "/stories/Why Rudrabhishek is one of the most requested Shiva rituals.png",
    excerpt: "From the first offering to the final aarti, a ritual viewed through its sequence.",
    excerptHi: "पहले अर्पण से अंतिम आरती तक, एक अनुष्ठान अपने क्रम के माध्यम से।",
  },
  {
    id: "home-puja",
    category: "Devotee Stories",
    title: "A puja performed 1,300 km away, but still close to home",
    titleHi: "1,300 किमी दूर संपन्न पूजा, फिर भी घर के करीब",
    read: "5 min",
    date: "Aug 18, 2026",
    image:
      "/stories/A puja performed 1,300 km away, but still close to home.png",
    excerpt: "One family’s reason for choosing a remote puja service for a milestone.",
    excerptHi: "किसी मील के पत्थर के लिए दूरस्थ पूजा सेवा चुनने वाले एक परिवार का कारण।",
  },
  {
    id: "diwali-lakshmi",
    category: "Festivals",
    title: "A calmer way to prepare for Diwali",
    titleHi: "दीवाली की तैयारी का एक शांत तरीका",
    read: "7 min",
    date: "Aug 11, 2026",
    image:
      "/stories/A calmer way to prepare for Diwali.png",
    excerpt: "How to bring the important ritual details forward before the festival rush.",
    excerptHi: "त्यौहार की भीड़ से पहले महत्वपूर्ण अनुष्ठान विवरण आगे कैसे लाएँ।",
  },
  {
    id: "annadanam",
    category: "Rituals / Puja Vidhi",
    title: "What happens when a puja includes Annadanam",
    titleHi: "जब पूजा में अन्नदान शामिल हो तब क्या होता है",
    read: "5 min",
    date: "Aug 07, 2026",
    image:
      "/stories/What happens when a puja includes Annadanam.png",
    excerpt: "A visual guide to the offering, preparation and community side of the ritual.",
    excerptHi: "अर्पण, तैयारी और अनुष्ठान के सामुदायिक पक्ष का दृश्य मार्गदर्शन।",
  },
  {
    id: "temple-morning",
    category: "Temple Histories",
    title: "Before sunrise: a temple morning in three sounds",
    titleHi: "सूर्योदय से पहले: तीन ध्वनियों में मंदिर की सुबह",
    read: "4 min",
    date: "Jul 28, 2026",
    image:
      "/stories/Before sunrise a temple morning in three sounds.png",
    excerpt: "Bell, conch and chant. A closer look at the rhythm of an early temple morning.",
    excerptHi: "घंटा, शंख और मंत्र। एक मंदिर की प्रातः की लय पर एक नज़दीकी नज़र।",
  },
  {
    id: "family-sankalp",
    category: "Devotee Stories",
    title: "The family Sankalp that crossed three cities",
    titleHi: "तीन शहरों को पार करने वाला पारिवारिक संकल्प",
    read: "6 min",
    date: "Jul 21, 2026",
    image:
      "/stories/The family Sankalp that crossed three cities.png",
    excerpt: "A family used one booking to bring siblings together for a shared intention.",
    excerptHi: "एक परिवार ने एक बुकिंग से भाई-बहनों को साझा संकल्प के लिए एक साथ लाया।",
  },
];
export const intentions = [
  "Peace & protection",
  "Health & well-being",
  "Wealth & prosperity",
  "Marriage & family",
  "Career & success",
  "Education",
  "New beginnings",
  "Ancestral peace",
  "Spiritual growth",
  "Dosha & remedy",
];
export const deities = [
  "Shiva",
  "Vishnu",
  "Krishna",
  "Ganesh",
  "Lakshmi",
  "Durga",
  "Hanuman",
  "Kali",
  "Navagraha",
  "Pitru",
];
// Hindi labels for deity filters / menus. Keys stay English so URLs + filtering
// keep working across languages.
export const deityHi = {
  Shiva: "शिव",
  Vishnu: "विष्णु",
  Krishna: "कृष्ण",
  Ganesh: "गणेश",
  Lakshmi: "लक्ष्मी",
  Durga: "दुर्गा",
  Hanuman: "हनुमान",
  Kali: "काली",
  Navagraha: "नवग्रह",
  Pitru: "पितृ",
};
export const social = [
  {
    label: "Instagram",
    type: "Reel",
    image:
      "/more/diya.png",
    copy: "Aarti in the last light of evening.",
  },
  {
    label: "YouTube",
    type: "Short",
    image:
      "/more/templeinside.png",
    copy: "Inside a temple morning ritual.",
  },
  {
    label: "Facebook",
    type: "Story",
    image:
      "/more/temple.png",
    copy: "A devotee’s first remote puja.",
  },
  {
    label: "WhatsApp",
    type: "Channel",
    image:
      "/more/ganesh.png",
    copy: "Festival reminders and live updates.",
  },
];

// Updated acharya list — replaces the placeholder scholars with the real
// profiles from Acharya.md (Amit Diwedy, Mohit Sharma, Chandra Shekhar
// Samavedula). Bilingual fields are exposed so the UI can switch EN/HI.
export const acharyas = [
  {
    id: "ranganath-tripathi",
    name: "Dr. Ranganath Tripathi",
    principal: true,
    tradition: "Vedic Karmakanda & Paurohitya",
    traditionHi: "वैदिक कर्मकांड एवं पौरोहित्य",
    place: "Varanasi",
    placeHi: "वाराणसी",
    approach: "Shastra · Tradition · Authenticity",
    approachHi: "शास्त्र · परंपरा · प्रामाणिकता",
    expertise: "Shradh · Pitru Karma · Kaal Sarp Shanti",
    expertiseHi: "श्राद्ध · पितृ कर्म · कालसर्प शांति",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Principal Vedacharya, Dharmaa Tribe",
    experienceHi: "प्रमुख वेदाचार्य, धर्मा ट्राइब",
    image: "/Acharya/Dr. rangnath.jpeg",
    qualifications: ["Yajurvedacharya — Karmakanda & Paurohitya", "Sahitya Acharya — Sanskrit Literature", "Rigvedacharya — Vedic Mantras", "Puranetihasacharya — Puranas & Itihasa", "Shikshashastri (B.Ed.) — Teacher Education", "Ph.D. (Vidyavaridhi) — Srauta Yajna research"],
    qualificationsHi: ["यजुर्वेदाचार्य — कर्मकांड एवं पौरोहित्य", "साहित्याचार्य — संस्कृत साहित्य", "ऋग्वेदाचार्य — वैदिक मंत्र", "पुराणेतिहासाचार्य — पुराण एवं इतिहास", "शिक्षाशास्त्री (B.Ed.) — शिक्षक शिक्षा", "Ph.D. (विद्यावारिधि) — श्रौत यज्ञ शोध"],
    expertiseFull: ["Vedic Karmakanda & Paurohitya", "Puja-Paath & Vedic Anushthans", "Shradh & Pitru Karmas", "Tripindi Shradh", "Pitru Dosha Nivaran", "Kaal Sarp Shanti Puja", "Mangal Shanti", "Graha Shanti & Vedic Anushthans", "Shastric Sanskaras", "Vedic Mantra Prayoga"],
    expertiseFullHi: ["वैदिक कर्मकांड एवं पौरोहित्य", "पूजा-पाठ एवं वैदिक अनुष्ठान", "श्राद्ध एवं पितृ कर्म", "त्रिपिंडी श्राद्ध", "पितृ दोष निवारण अनुष्ठान", "कालसर्प शांति पूजा", "मंगल शांति", "ग्रह शांति एवं वैदिक अनुष्ठान", "शास्त्रीय संस्कार", "वैदिक मंत्र प्रयोग"],
    bio: "Dr. Ranganath Tripathi is a distinguished Sanskrit scholar and Vedic ritual specialist — Yajurvedacharya, Rigvedacharya, Sahitya Acharya and Puranetihasacharya, with Shikshashastri (B.Ed.) and Ph.D. (Vidyavaridhi) on Śrauta Yajña. Trained entirely in the Sanskrit medium from secondary level through Acharya, he conducts Shradh, Pitru Karma, Tripindi Shradh, Kaal Sarp Shanti, Mangal and Graha Shanti strictly by Shastric vidhi. As Principal Vedacharya he anchors Dharmaa Tribe's rituals in Shastra, tradition, mantra and authenticity, and regularly presents at national and international Sanskrit seminars.",
    bioHi:
      "डॉ. रंगनाथ त्रिपाठी प्रतिष्ठित संस्कृत विद्वान और वैदिक अनुष्ठान विशेषज्ञ हैं — यजुर्वेदाचार्य, ऋग्वेदाचार्य, साहित्याचार्य और पुराणेतिहासाचार्य, साथ ही शिक्षाशास्त्री (B.Ed.) एवं श्रौत यज्ञ पर Ph.D. (विद्यावारिधि)। माध्यमिक से आचार्य तक संपूर्ण शिक्षा संस्कृत माध्यम से — वे श्राद्ध, पितृ कर्म, त्रिपिंडी श्राद्ध, कालसर्प शांति, मंगल और ग्रह शांति शास्त्रोक्त विधि से संपन्न कराते हैं। प्रमुख वेदाचार्य के रूप में वे धर्मा ट्राइब के अनुष्ठानों को शास्त्र, परंपरा, मंत्र और प्रामाणिकता में स्थिर रखते हैं और राष्ट्रीय-अंतरराष्ट्रीय संस्कृत संगोष्ठियों में नियमित भाग लेते हैं।",
  },
  {
    id: "omkar-nath-tiwari",
    name: "Acharya Omkar Nath Tiwari",
    tradition: "Vedic Karmakanda & Puja-Paath",
    traditionHi: "वैदिक कर्मकांड एवं पूजा-पाठ",
    place: "Trimbakeshwar, Nashik",
    placeHi: "त्र्यंबकेश्वर, नासिक",
    approach: "Knowledge · Discipline · Authenticity",
    approachHi: "ज्ञान · अनुशासन · प्रामाणिकता",
    expertise: "Karmakanda · Tripindi Shraddha · Graha Shanti",
    expertiseHi: "कर्मकांड · त्रिपिंडी श्राद्ध · ग्रह शांति",
    lineage: "Banaras Hindu University (BHU), Varanasi",
    lineageHi: "काशी हिन्दू विश्वविद्यालय, वाराणसी",
    experience: "M.A. Sanskrit · Vyakarana · Sahitya · Yoga",
    experienceHi: "एम.ए. संस्कृत · व्याकरण · साहित्य · योग",
    image: "/Acharya/omkar nath Tiwari.jpeg",
    qualifications: ["Acharya — Banaras Hindu University (BHU), Varanasi", "Vyakarana Acharya — Sanskrit Grammar", "Sahitya Acharya — Sanskrit Literature", "Yoga Acharya — Yogic Studies", "Shikshashastri (B.Ed.) — Teacher Education", "M.A. in Sanskrit"],
    qualificationsHi: ["आचार्य — काशी हिन्दू विश्वविद्यालय, वाराणसी", "व्याकरणाचार्य — संस्कृत व्याकरण", "साहित्याचार्य — संस्कृत साहित्य", "योगाचार्य — योग अध्ययन", "शिक्षाशास्त्री (B.Ed.) — शिक्षक शिक्षा", "एम.ए. संस्कृत"],
    expertiseFull: ["Vedic Karmakanda & Puja-Paath", "Kaal Sarp Shanti Puja", "Tripindi Shradh", "Pitru Dosha Nivaran", "Mangal Shanti", "Graha Shanti & Special Anushthans", "Sanskaras & Shastric Puja Vidhi"],
    expertiseFullHi: ["वैदिक कर्मकांड एवं पूजा-पाठ", "कालसर्प शांति पूजा", "त्रिपिंडी श्राद्ध", "पितृ दोष निवारण अनुष्ठान", "मंगल शांति", "ग्रह शांति एवं विशेष वैदिक अनुष्ठान", "संस्कार एवं शास्त्रोक्त पूजन-विधि"],
    bio: "Acharya Omkar Nath Tiwari holds the Acharya degree from BHU Varanasi with complete Sanskrit-medium education, plus Vyakarana, Sahitya and Yoga Acharya qualifications, Shikshashastri (B.Ed.) and M.A. in Sanskrit. Based in Trimbakeshwar, Nashik, he conducts Karmakanda, Kaal Sarp Shanti, Tripindi Shraddha, Pitru Dosha Nivaran, Mangal and Graha Shanti per Shastric vidhi.",
    bioHi:
      "आचार्य ओंकार नाथ तिवारी काशी हिन्दू विश्वविद्यालय से आचार्य हैं — संपूर्ण संस्कृत-माध्यम शिक्षा के साथ व्याकरण, साहित्य और योग में आचार्य उपाधियाँ, शिक्षाशास्त्री (B.Ed.) एवं एम.ए. संस्कृत। त्र्यंबकेश्वर, नासिक निवासी — कर्मकांड, कालसर्प शांति, त्रिपिंडी श्राद्ध, पितृ दोष निवारण, मंगल और ग्रह शांति शास्त्रोक्त विधि से संपन्न कराते हैं।",
  },
  {
    id: "prem-narayan-tripathi",
    name: "Acharya Prem Narayan Tripathi",
    tradition: "Vedic Karmakanda & Puja-Paath",
    traditionHi: "वैदिक कर्मकांड एवं पूजा-पाठ",
    place: "Uttar Pradesh",
    placeHi: "उत्तर प्रदेश",
    approach: "Knowledge · Discipline · Authenticity",
    approachHi: "ज्ञान · अनुशासन · प्रामाणिकता",
    expertise: "Karmakanda · Pitru Dosha Nivaran · Sanskaras",
    expertiseHi: "कर्मकांड · पितृ दोष निवारण · संस्कार",
    lineage: "Banaras Hindu University (BHU), Varanasi",
    lineageHi: "काशी हिन्दू विश्वविद्यालय, वाराणसी",
    experience: "Veda Pandit Awardee, Govt. of UP · Honoured by Sringeri Math",
    experienceHi: "वेद पण्डित पुरस्कार, उ.प्र. शासन · श्रृंगेरी मठ सम्मानित",
    image: "/Acharya/Prem Narayan Tripathi.jpeg",
    qualifications: ["Acharya — Banaras Hindu University (BHU), Varanasi", "Shikshashastri (B.Ed.)", "Veda Pandit Awardee — Govt. of Uttar Pradesh", "Honoured by Sringeri Math as Veda Pandit"],
    qualificationsHi: ["आचार्य — काशी हिन्दू विश्वविद्यालय, वाराणसी", "शिक्षाशास्त्री (B.Ed.)", "वेद पण्डित पुरस्कार — उत्तर प्रदेश शासन", "श्रृंगेरी मठ द्वारा वेद पण्डित सम्मान"],
    expertiseFull: ["Vedic Karmakanda & Puja-Paath", "Kaal Sarp Shanti Puja", "Tripindi Shradh", "Pitru Dosha Nivaran", "Mangal Shanti", "Graha Shanti & Special Anushthans", "Sanskaras & Shastric Puja Vidhi"],
    expertiseFullHi: ["वैदिक कर्मकांड एवं पूजा-पाठ", "कालसर्प शांति पूजा", "त्रिपिंडी श्राद्ध", "पितृ दोष निवारण अनुष्ठान", "मंगल शांति", "ग्रह शांति एवं विशेष वैदिक अनुष्ठान", "संस्कार एवं शास्त्रोक्त पूजन-विधि"],
    bio: "Acharya Prem Narayan Tripathi holds the Acharya degree from BHU Varanasi with complete Sanskrit-medium education and Shikshashastri (B.Ed.). Honoured with the Veda Pandit Award by the Government of Uttar Pradesh and by Sringeri Math as a Veda Pandit, he conducts Karmakanda, Tripindi Shraddha, Pitru Dosha Nivaran, Kaal Sarp and Graha Shanti with strict regard for Shastra and Sankalpa.",
    bioHi:
      "आचार्य प्रेम नारायण त्रिपाठी काशी हिन्दू विश्वविद्यालय से आचार्य हैं — संपूर्ण संस्कृत-माध्यम शिक्षा एवं शिक्षाशास्त्री (B.Ed.)। उत्तर प्रदेश शासन के वेद पण्डित पुरस्कार तथा श्रृंगेरी मठ द्वारा वेद पण्डित सम्मान से सम्मानित — कर्मकांड, त्रिपिंडी श्राद्ध, पितृ दोष निवारण, कालसर्प और ग्रह शांति शास्त्र एवं संकल्प के पूर्ण सम्मान के साथ संपन्न कराते हैं।",
  },
  {
    id: "dileep-pandey",
    name: "Acharya Dileep Pandey",
    tradition: "Vedic Karmakanda & Puja-Paath",
    traditionHi: "वैदिक कर्मकांड एवं पूजा-पाठ",
    place: "Varanasi",
    placeHi: "वाराणसी",
    approach: "Knowledge · Discipline · Authenticity",
    approachHi: "ज्ञान · अनुशासन · प्रामाणिकता",
    expertise: "Karmakanda · Kaal Sarp Shanti · Mangal Shanti",
    expertiseHi: "कर्मकांड · कालसर्प शांति · मंगल शांति",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Acharya · Sanskrit-medium scholar",
    experienceHi: "आचार्य · संस्कृत-माध्यम विद्वान",
    image: "/Acharya/Dileep Pandey.jpeg",
    qualifications: ["Acharya — Sampurnanand Sanskrit University, Varanasi", "Complete Sanskrit-medium education (secondary to Acharya)"],
    qualificationsHi: ["आचार्य — सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी", "माध्यमिक से आचार्य तक संपूर्ण संस्कृत-माध्यम शिक्षा"],
    expertiseFull: ["Vedic Karmakanda & Puja-Paath", "Kaal Sarp Shanti Puja", "Tripindi Shradh", "Pitru Dosha Nivaran", "Mangal Shanti", "Graha Shanti & Special Anushthans", "Sanskaras & Shastric Puja Vidhi"],
    expertiseFullHi: ["वैदिक कर्मकांड एवं पूजा-पाठ", "कालसर्प शांति पूजा", "त्रिपिंडी श्राद्ध", "पितृ दोष निवारण अनुष्ठान", "मंगल शांति", "ग्रह शांति एवं विशेष वैदिक अनुष्ठान", "संस्कार एवं शास्त्रोक्त पूजन-विधि"],
    bio: "Acharya Dileep Pandey holds the Acharya degree from Sampurnanand Sanskrit University, Varanasi, with complete Sanskrit-medium education from secondary level through Acharya. Grounded in Sanskrit scholarship and traditional Vedic ritual practice, he conducts Karmakanda, Puja-Paath, Tripindi Shraddha, Pitru Dosha Nivaran and Graha Shanti per established Vedic traditions.",
    bioHi:
      "आचार्य दिलीप पाण्डेय सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी से आचार्य हैं — माध्यमिक से आचार्य तक संपूर्ण संस्कृत-माध्यम शिक्षा। संस्कृत विद्वत्ता और पारंपरिक वैदिक अनुष्ठान पद्धति में निहित — कर्मकांड, पूजा-पाठ, त्रिपिंडी श्राद्ध, पितृ दोष निवारण और ग्रह शांति स्थापित वैदिक परंपराओं के अनुसार संपन्न कराते हैं।",
  },
  {
    id: "shubham-tripathi",
    name: "Acharya Shubham Tripathi",
    tradition: "Vedic Karmakanda & Sanskaras",
    traditionHi: "वैदिक कर्मकांड एवं संस्कार",
    place: "Prayagraj",
    placeHi: "प्रयागराज",
    approach: "Authenticity · Devotion · Discipline",
    approachHi: "प्रामाणिकता · भक्ति · अनुशासन",
    expertise: "Samskaras · Rudrabhishek · Vivah Sanskar",
    expertiseHi: "संस्कार · रुद्राभिषेक · विवाह संस्कार",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Shastri · Acharya · Shodasha Samskaras",
    experienceHi: "शास्त्री · आचार्य · षोडश संस्कार",
    image: "/Acharya/Shubham Tripathi.jpg",
    qualifications: ["Uttar Madhyama — Shri Mahant Vicharanand Sanskrit Vidyalaya, Prayagraj", "Shastri — Sampurnanand Sanskrit University, Varanasi", "Acharya — Sampurnanand Sanskrit University, Varanasi"],
    qualificationsHi: ["उत्तर मध्यमा — श्री महंत विचारानंद संस्कृत विद्यालय, प्रयागराज", "शास्त्री — सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी", "आचार्य — सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी"],
    expertiseFull: ["Shodasha Samskaras", "Karmakanda & Puja Vidhi", "Rudrabhishek", "Yajna & Havan", "Vedic Anushthana", "Vivah Sanskar", "Griha Pravesh & Vastu Puja", "Shanti Path & Shanti Anushthana", "Shastric Puja Vidhi", "Traditional Samskaras"],
    expertiseFullHi: ["षोडश संस्कार", "कर्मकांड एवं पूजा-विधि", "रुद्राभिषेक", "यज्ञ एवं हवन", "वैदिक अनुष्ठान", "विवाह संस्कार", "गृह प्रवेश एवं वास्तु पूजन", "शांति पाठ एवं शांति अनुष्ठान", "शास्त्रोक्त पूजन-विधि", "पारंपरिक संस्कार"],
    bio: "Acharya Shubham Tripathi is a Sanskrit scholar and experienced Acharya specializing in Vedic rituals, Karmakanda and Sanatan ceremonies — Shastri and Acharya from Sampurnanand Sanskrit University, Varanasi. He conducts Shodasha Samskaras, Rudrabhishek, Yajna-Havan, Vivah Sanskar, Griha Pravesh, Shanti Anushthans and Vedic Anushthana with correct procedure, devotion and ritual discipline, so the Yajamana and family can participate meaningfully.",
    bioHi:
      "आचार्य शुभम त्रिपाठी संस्कृत विद्वान और अनुभवी आचार्य हैं — वैदिक अनुष्ठान, कर्मकांड और सनातन समारोहों के विशेषज्ञ; सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी से शास्त्री एवं आचार्य। वे षोडश संस्कार, रुद्राभिषेक, यज्ञ-हवन, विवाह संस्कार, गृह प्रवेश, शांति अनुष्ठान और वैदिक अनुष्ठान सही विधि, भक्ति और अनुशासन के साथ संपन्न कराते हैं, ताकि यजमान और परिवार अर्थपूर्ण सहभागिता कर सकें।",
  },
  {
    id: "manish-pandey",
    name: "Acharya Manish Pandey",
    tradition: "Vedic Karmakanda & Sanskaras",
    traditionHi: "वैदिक कर्मकांड एवं संस्कार",
    place: "Chhittupur, Kashi Vishwanath Dham, Varanasi",
    placeHi: "छित्तूपुर, काशी विश्वनाथ धाम, वाराणसी",
    approach: "Authenticity · Devotion · Discipline",
    approachHi: "प्रामाणिकता · भक्ति · अनुशासन",
    expertise: "Samskaras · Rudrabhishek · Vivah Sanskar",
    expertiseHi: "संस्कार · रुद्राभिषेक · विवाह संस्कार",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Shastri · B.Ed. · Shodasha Samskaras",
    experienceHi: "शास्त्री · B.Ed. · षोडश संस्कार",
    image: "/Acharya/Manish Pandey.jpeg",
    qualifications: ["Shastri — Sampurnanand Sanskrit University, Varanasi", "Uttar Madhyama — Shri Janta Sanskrit Mahavidyalaya, Varanasi", "B.Ed. — Shri Gauri Shankar Mahavidyalaya, Jaunpur"],
    qualificationsHi: ["शास्त्री — सम्पूर्णानन्द संस्कृत विश्वविद्यालय, वाराणसी", "उत्तर मध्यमा — श्री जनता संस्कृत महाविद्यालय, वाराणसी", "B.Ed. — श्री गौरी शंकर महाविद्यालय, जौनपुर"],
    expertiseFull: ["Shodasha Samskaras", "Karmakanda & Puja Vidhi", "Rudrabhishek", "Yajna & Havan", "Vedic Rituals & Anushthans", "Vivah Samskara", "Griha Pravesh & Vastu Pujas", "Shanti Path & Shanti Anushthans", "Shastric Puja Vidhi", "Traditional Samskaras"],
    expertiseFullHi: ["षोडश संस्कार", "कर्मकांड एवं पूजा-विधि", "रुद्राभिषेक", "यज्ञ एवं हवन", "वैदिक अनुष्ठान", "विवाह संस्कार", "गृह प्रवेश एवं वास्तु पूजन", "शांति पाठ एवं शांति अनुष्ठान", "शास्त्रोक्त पूजन-विधि", "पारंपरिक संस्कार"],
    phone: "+91 98359 22210",
    bio: "Acharya Manish Pandey is a trained Sanskrit scholar and Vedic ritual practitioner — Shastri from Sampurnanand Sanskrit University with Sanskrit-medium schooling and B.Ed. Based at Chhittupur, Kashi Vishwanath Dham, he conducts Shodasha Samskaras, Rudrabhishek, Yajna-Havan, Vivah Sanskar, Griha Pravesh and Shanti Anushthans with authenticity, devotion and proper ritual methodology.",
    bioHi:
      "आचार्य मनीष पाण्डेय प्रशिक्षित संस्कृत विद्वान और वैदिक अनुष्ठान साधक हैं — सम्पूर्णानन्द संस्कृत विश्वविद्यालय से शास्त्री, संस्कृत-माध्यम शिक्षा एवं B.Ed.। काशी विश्वनाथ धाम, छित्तूपुर निवासी — षोडश संस्कार, रुद्राभिषेक, यज्ञ-हवन, विवाह संस्कार, गृह प्रवेश और शांति अनुष्ठान शास्त्रोक्त विधि एवं सनातन परंपरा के अनुसार संपन्न कराते हैं। “शास्त्रोक्त विधि • सनातन वैदिक परंपरा • श्रद्धा एवं विधिपूर्वक अनुष्ठान”।",
  },
  {
    id: "rupesh-pandey",
    name: "Vaidik Rupesh Pandey",
    tradition: "Vedic Karmakanda & Sanskaras",
    traditionHi: "वैदिक कर्मकांड एवं संस्कार",
    place: "Shri Kashi Vishwanath Dham, Varanasi",
    placeHi: "श्री काशी विश्वनाथ धाम, वाराणसी",
    approach: "Knowledge · Discipline · Devotion",
    approachHi: "ज्ञान · अनुशासन · भक्ति",
    expertise: "Samskaras · Rudrabhishek · Shanti Anushthan",
    expertiseHi: "संस्कार · रुद्राभिषेक · शांति अनुष्ठान",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Samavedacharya · Shastri · B.Ed.",
    experienceHi: "सामवेदाचार्य · शास्त्री · B.Ed.",
    image: "/Acharya/Rupesh Pandey.jpeg",
    qualifications: ["Samavedacharya", "Vedic Karmakanda", "Shastri — Sampurnanand Sanskrit University, Varanasi", "Uttar Madhyama — Shri Janta Sanskrit Mahavidyalaya, Varanasi", "Shikshashastri (B.Ed.) — Shri Gauri Shankar Mahavidyalaya, Jaunpur"],
    qualificationsHi: ["सामवेदाचार्य", "वैदिक कर्मकांड", "शास्त्री — सम्पूर्णानन्द संस्कृत विश्वविद्यालय, वाराणसी", "उत्तर मध्यमा — श्री जनता संस्कृत महाविद्यालय, वाराणसी", "शिक्षाशास्त्री (B.Ed.) — श्री गौरी शंकर महाविद्यालय, जौनपुर"],
    expertiseFull: ["Shodasha Samskaras", "Karmakanda & Puja Vidhi", "Rudrabhishek", "Yajna & Havan", "Vedic Rituals & Anushthans", "Vivah Samskara", "Griha Pravesh & Vastu Pujas", "Shanti Path & Shanti Anushthans", "Shastric Puja Vidhi", "Traditional Samskaras"],
    expertiseFullHi: ["षोडश संस्कार", "कर्मकांड एवं पूजा-विधि", "रुद्राभिषेक", "यज्ञ एवं हवन", "वैदिक अनुष्ठान", "विवाह संस्कार", "गृह प्रवेश एवं वास्तु पूजन", "शांति पाठ एवं शांति अनुष्ठान", "शास्त्रोक्त पूजन-विधि", "पारंपरिक संस्कार"],
    phone: "+91 89533 03796",
    bio: "Vaidik Rupesh Pandey is a trained Sanskrit scholar and Vedic ritual practitioner — Samavedacharya and Shastri from Sampurnanand Sanskrit University with Sanskrit-medium schooling and Shikshashastri (B.Ed.). Based at Shri Kashi Vishwanath Dham, he conducts Shodasha Samskaras, Karmakanda, Rudrabhishek, Vivah Sanskar and Shanti Anushthans per Shastric procedure and Sanatan tradition.",
    bioHi:
      "वैदिक रूपेश पाण्डेय प्रशिक्षित संस्कृत विद्वान और वैदिक अनुष्ठान साधक हैं — सम्पूर्णानन्द संस्कृत विश्वविद्यालय से सामवेदाचार्य एवं शास्त्री, संस्कृत-माध्यम शिक्षा तथा शिक्षाशास्त्री (B.Ed.)। श्री काशी विश्वनाथ धाम निवासी — षोडश संस्कार, कर्मकांड, रुद्राभिषेक, विवाह संस्कार और शांति अनुष्ठान शास्त्रोक्त विधि एवं सनातन परंपरा के अनुसार संपन्न कराते हैं। “शास्त्रोक्त विधि • सनातन वैदिक परंपरा • श्रद्धा एवं विधिपूर्वक अनुष्ठान”।",
  },
  {
    id: "rishabh-pandey",
    name: "Shri Rishabh Pandey",
    tradition: "Vedic Karmakanda & Sanskaras",
    traditionHi: "वैदिक कर्मकांड एवं संस्कार",
    place: "Azamgarh, Uttar Pradesh",
    placeHi: "आजमगढ़, उत्तर प्रदेश",
    approach: "Sincerity · Discipline · Tradition",
    approachHi: "निष्ठा · अनुशासन · परंपरा",
    expertise: "Samskaras · Rudrabhishek · Griha Pravesh",
    expertiseHi: "संस्कार · रुद्राभिषेक · गृह प्रवेश",
    lineage: "Shri Padmavaidyam Tirth Veda Vidyalaya, Gorakhpur",
    lineageHi: "श्री पद्मवैद्यम् तीर्थ वेद विद्यालय, गोरखपुर",
    experience: "Shastri · Sanskrit-medium scholar",
    experienceHi: "शास्त्री · संस्कृत-माध्यम विद्वान",
    image: "/Acharya/Rishabh Pandey.jpeg",
    qualifications: ["Shastri — Shri Padmavaidyam Tirth Veda Vidyalaya, Gorakhpur", "Uttar Madhyama — Sanskrit-medium education"],
    qualificationsHi: ["शास्त्री — श्री पद्मवैद्यम् तीर्थ वेद विद्यालय, गोरखपुर", "उत्तर मध्यमा — संस्कृत-माध्यम शिक्षा"],
    expertiseFull: ["Shodasha Samskaras", "Karmakanda & Puja Vidhi", "Rudrabhishek", "Yajna & Havan", "Vedic Rituals & Anushthans", "Vivah Samskara", "Griha Pravesh & Vastu Pujas", "Shanti Path & Shanti Anushthans", "Shastric Puja Vidhi", "Traditional Samskaras"],
    expertiseFullHi: ["षोडश संस्कार", "कर्मकांड एवं पूजा-विधि", "रुद्राभिषेक", "यज्ञ एवं हवन", "वैदिक अनुष्ठान", "विवाह संस्कार", "गृह प्रवेश एवं वास्तु पूजन", "शांति पाठ एवं शांति अनुष्ठान", "शास्त्रोक्त पूजन-विधि", "पारंपरिक संस्कार"],
    bio: "Shri Rishabh Pandey is a trained Sanskrit scholar and Vedic ritual practitioner — Shastri from Shri Padmavaidyam Tirth Veda Vidyalaya, Gorakhpur, with Sanskrit-medium education up to Uttar Madhyama. Based in Azamgarh, he conducts Shodasha Samskaras, Karmakanda, Rudrabhishek, Vivah Sanskar and Shanti Anushthans with sincerity and strict adherence to Shastric procedure.",
    bioHi:
      "श्री ऋषभ पाण्डेय प्रशिक्षित संस्कृत विद्वान और वैदिक अनुष्ठान साधक हैं — श्री पद्मवैद्यम् तीर्थ वेद विद्यालय, गोरखपुर से शास्त्री, उत्तर मध्यमा तक संस्कृत-माध्यम शिक्षा। आजमगढ़ निवासी — षोडश संस्कार, कर्मकांड, रुद्राभिषेक, विवाह संस्कार और शांति अनुष्ठान निष्ठा एवं शास्त्रोक्त विधि के पूर्ण पालन के साथ संपन्न कराते हैं।",
  },
  {
    id: "shubham-tiwari",
    name: "Shri Shubham Tiwari",
    tradition: "Vedic Karmakanda & Sanskaras",
    traditionHi: "वैदिक कर्मकांड एवं संस्कार",
    place: "Varanasi, Uttar Pradesh",
    placeHi: "वाराणसी, उत्तर प्रदेश",
    approach: "Sincerity · Discipline · Tradition",
    approachHi: "निष्ठा · अनुशासन · परंपरा",
    expertise: "Samskaras · Yajna-Havan · Vivah Sanskar",
    expertiseHi: "संस्कार · यज्ञ-हवन · विवाह संस्कार",
    lineage: "Maharishi Sandipani Ved Vidya Pratishthan, Ujjain",
    lineageHi: "महर्षि सान्दीपनि वेद विद्या प्रतिष्ठान, उज्जैन",
    experience: "Shastri · Sanskrit-medium scholar",
    experienceHi: "शास्त्री · संस्कृत-माध्यम विद्वान",
    image: "/Acharya/Shri Shubham Tiwari.jpeg",
    qualifications: ["Shastri — Maharishi Sandipani Ved Vidya Pratishthan, Ujjain", "Uttar Madhyama — Sanskrit-medium education"],
    qualificationsHi: ["शास्त्री — महर्षि सान्दीपनि वेद विद्या प्रतिष्ठान, उज्जैन", "उत्तर मध्यमा — संस्कृत-माध्यम शिक्षा"],
    expertiseFull: ["Shodasha Samskaras", "Karmakanda & Puja Vidhi", "Rudrabhishek", "Yajna & Havan", "Vedic Rituals & Anushthans", "Vivah Samskara", "Griha Pravesh & Vastu Pujas", "Shanti Path & Shanti Anushthans", "Shastric Puja Vidhi", "Traditional Samskaras"],
    expertiseFullHi: ["षोडश संस्कार", "कर्मकांड एवं पूजा-विधि", "रुद्राभिषेक", "यज्ञ एवं हवन", "वैदिक अनुष्ठान", "विवाह संस्कार", "गृह प्रवेश एवं वास्तु पूजन", "शांति पाठ एवं शांति अनुष्ठान", "शास्त्रोक्त पूजन-विधि", "पारंपरिक संस्कार"],
    bio: "Shri Shubham Tiwari is a traditionally trained Sanskrit scholar and Vedic ritual practitioner — Shastri via Maharishi Sandipani Rashtriya Ved Vidya Pratishthan, Ujjain, with Sanskrit-medium education. Based in Varanasi, he conducts Shodasha Samskaras, Rudrabhishek, Yajna-Havan, Vivah Sanskar, Griha Pravesh and Shanti Anushthans with sincere devotion to Shastric procedure.",
    bioHi:
      "श्री शुभम तिवारी परंपरागत प्रशिक्षित संस्कृत विद्वान और वैदिक अनुष्ठान साधक हैं — महर्षि सान्दीपनि राष्ट्रीय वेद विद्या प्रतिष्ठान, उज्जैन से शास्त्री, संस्कृत-माध्यम शिक्षा। वाराणसी निवासी — षोडश संस्कार, रुद्राभिषेक, यज्ञ-हवन, विवाह संस्कार, गृह प्रवेश और शांति अनुष्ठान शास्त्रोक्त विधि के प्रति पूर्ण निष्ठा के साथ संपन्न कराते हैं।",
  },
  {
    id: "ravishankar-shukla",
    name: "Acharya Ravishankar Shukla",
    tradition: "Vedic Karmakanda & Shanti Anushthan",
    traditionHi: "वैदिक कर्मकांड एवं शांति अनुष्ठान",
    place: "Uttar Pradesh",
    placeHi: "उत्तर प्रदेश",
    approach: "Scholarship · Discipline · Authenticity",
    approachHi: "विद्वत्ता · अनुशासन · प्रामाणिकता",
    expertise: "Kaal Sarp Shanti · Tripindi · Pitru Dosha Nivaran",
    expertiseHi: "कालसर्प शांति · त्रिपिंडी · पितृ दोष निवारण",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Vedacharya · Sahityacharya · Vedantacharya",
    experienceHi: "वेदाचार्य · साहित्याचार्य · वेदान्ताचार्य",
    image: "/Acharya/Ravishankar Shukla.jpeg",
    qualifications: ["Vedacharya — Vedic studies", "Sahityacharya — Sanskrit literature", "Vedantacharya — Vedanta"],
    qualificationsHi: ["वेदाचार्य — वैदिक अध्ययन", "साहित्याचार्य — संस्कृत साहित्य", "वेदान्ताचार्य — वेदान्त"],
    expertiseFull: ["Karmakanda & Puja Vidhi", "Kaal Sarp Shanti Puja", "Tripindi Shradh", "Pitru Dosha Nivaran", "Mangal Shanti", "Graha Shanti & Special Anushthans", "Traditional Samskaras", "Shastric Puja Vidhi"],
    expertiseFullHi: ["कर्मकांड एवं पूजा-पाठ", "कालसर्प शांति पूजा", "त्रिपिंडी श्राद्ध", "पितृ दोष निवारण अनुष्ठान", "मंगल शांति", "ग्रह शांति एवं विशेष वैदिक अनुष्ठान", "पारंपरिक संस्कार", "शास्त्रोक्त पूजन-विधि"],
    bio: "Acharya Ravishankar Shukla is an accomplished Sanskrit scholar — Vedacharya, Sahityacharya and Vedantacharya from Sampurnanand Sanskrit University with entire Sanskrit-medium education. He specialises in ancestral rites and Shanti ceremonies: Kaal Sarp Shanti, Tripindi Shraddha, Pitru Dosha Nivaran, Mangal and Graha Shanti, conducted with deep traditional scholarship and disciplined Shastric practice.",
    bioHi:
      "आचार्य रविशंकर शुक्ल प्रवीण संस्कृत विद्वान हैं — सम्पूर्णानंद संस्कृत विश्वविद्यालय से वेदाचार्य, साहित्याचार्य एवं वेदान्ताचार्य, संपूर्ण संस्कृत-माध्यम शिक्षा। पितृ अनुष्ठानों और शांति समारोहों के विशेषज्ञ — कालसर्प शांति, त्रिपिंडी श्राद्ध, पितृ दोष निवारण, मंगल और ग्रह शांति गहन पारंपरिक विद्वत्ता एवं अनुशासित शास्त्रीय साधना के साथ संपन्न कराते हैं।",
  },
  {
    id: "ravikant-tiwari",
    name: "Shri Ravikant Tiwari",
    tradition: "Jyotisha & Vedic Karmakanda",
    traditionHi: "ज्योतिष एवं वैदिक कर्मकांड",
    place: "Shri Kashi Vishwanath Dham, Varanasi",
    placeHi: "श्री काशी विश्वनाथ धाम, वाराणसी",
    approach: "Scripture · Discipline · Devotion",
    approachHi: "शास्त्र · अनुशासन · भक्ति",
    expertise: "Jyotisha · Samskaras · Shanti Anushthan",
    expertiseHi: "ज्योतिष · संस्कार · शांति अनुष्ठान",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Jyotishacharya · Shastri · Karmakanda",
    experienceHi: "ज्योतिषाचार्य · शास्त्री · कर्मकांड",
    image: "/Acharya/Ravikant Tiwari.jpeg",
    qualifications: ["Jyotishacharya — Vedic astrology", "Shastri — Sampurnanand Sanskrit University, Varanasi", "Uttar Madhyama — Sanskrit-medium education", "Vedic Karmakanda"],
    qualificationsHi: ["ज्योतिषाचार्य — वैदिक ज्योतिष", "शास्त्री — सम्पूर्णानन्द संस्कृत विश्वविद्यालय, वाराणसी", "उत्तर मध्यमा — संस्कृत-माध्यम शिक्षा", "वैदिक कर्मकांड"],
    expertiseFull: ["Shodasha Samskaras", "Karmakanda & Puja Vidhi", "Rudrabhishek", "Yajna & Havan", "Vedic Rituals & Anushthans", "Vivah Samskara", "Griha Pravesh & Vastu Pujas", "Shanti Path & Shanti Anushthans", "Shastric Puja Vidhi", "Traditional Samskaras"],
    expertiseFullHi: ["षोडश संस्कार", "कर्मकांड एवं पूजा-विधि", "रुद्राभिषेक", "यज्ञ एवं हवन", "वैदिक अनुष्ठान", "विवाह संस्कार", "गृह प्रवेश एवं वास्तु पूजन", "शांति पाठ एवं शांति अनुष्ठान", "शास्त्रोक्त पूजन-विधि", "पारंपरिक संस्कार"],
    bio: "Shri Ravikant Tiwari is a traditionally trained Sanskrit scholar — Jyotishacharya and Shastri from Sampurnanand Sanskrit University with Sanskrit-medium schooling. Based at Shri Kashi Vishwanath Dham, he combines Jyotisha with Vedic Karmakanda across Shodasha Samskaras, Rudrabhishek, Vivah Sanskar and Shanti Anushthans with scriptural understanding and disciplined practice.",
    bioHi:
      "श्री रविकान्त तिवारी परंपरागत प्रशिक्षित संस्कृत विद्वान हैं — सम्पूर्णानंद संस्कृत विश्वविद्यालय से ज्योतिषाचार्य एवं शास्त्री, संस्कृत-माध्यम शिक्षा। श्री काशी विश्वनाथ धाम निवासी — ज्योतिष को वैदिक कर्मकांड के साथ जोड़कर षोडश संस्कार, रुद्राभिषेक, विवाह संस्कार और शांति अनुष्ठान शास्त्रीय समझ एवं अनुशासित साधना के साथ संपन्न कराते हैं।",
  },
  {
    id: "vishnu-narayan-kaushik",
    name: "Shri Vishnu Narayan Kaushik",
    tradition: "Vedic Studies · Jyotisha · Karmakanda",
    traditionHi: "वैदिक अध्ययन · ज्योतिष · कर्मकांड",
    place: "Mahavir Nagar, Hingoli, Maharashtra",
    placeHi: "महावीर नगर, हिंगोली, महाराष्ट्र",
    approach: "Knowledge · Discipline · Practice",
    approachHi: "ज्ञान · अनुशासन · साधना",
    expertise: "Samskaras · Rudrabhishek · Shanti Anushthan",
    expertiseHi: "संस्कार · रुद्राभिषेक · शांति अनुष्ठान",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Vedacharya · Jyotishacharya · Shastri",
    experienceHi: "वेदाचार्य · ज्योतिषाचार्य · शास्त्री",
    image: "/Acharya/Vishnu Narayan Kaushik.jpeg",
    qualifications: ["Shastri — Sampurnanand Sanskrit University, Varanasi", "Uttar Madhyama — Sanskrit-medium education", "Vedacharya — Vedic studies", "Jyotishacharya — Jyotisha"],
    qualificationsHi: ["शास्त्री — सम्पूर्णानन्द संस्कृत विश्वविद्यालय, वाराणसी", "उत्तर मध्यमा — संस्कृत-माध्यम शिक्षा", "वेदाचार्य — वैदिक अध्ययन", "ज्योतिषाचार्य — ज्योतिष"],
    expertiseFull: ["Shodasha Samskaras", "Karmakanda & Puja Vidhi", "Rudrabhishek", "Yajna & Havan", "Vedic Rituals & Anushthans", "Vivah Samskara", "Griha Pravesh & Vastu Pujas", "Shanti Path & Shanti Anushthans", "Shastric Puja Vidhi", "Traditional Samskaras"],
    expertiseFullHi: ["षोडश संस्कार", "कर्मकांड एवं पूजा-विधि", "रुद्राभिषेक", "यज्ञ एवं हवन", "वैदिक अनुष्ठान", "विवाह संस्कार", "गृह प्रवेश एवं वास्तु पूजन", "शांति पाठ एवं शांति अनुष्ठान", "शास्त्रोक्त पूजन-विधि", "पारंपरिक संस्कार"],
    bio: "Shri Vishnu Narayan Kaushik is a traditionally trained Sanskrit scholar — Shastri, Vedacharya and Jyotishacharya from Sampurnanand Sanskrit University with Sanskrit-medium schooling. Based in Hingoli, Maharashtra, he brings well-rounded Vedic knowledge and disciplined Shastric practice to Shodasha Samskaras, Rudrabhishek, Vivah Sanskar and Shanti rituals.",
    bioHi:
      "श्री विष्णु नारायण कौशिक परंपरागत प्रशिक्षित संस्कृत विद्वान हैं — सम्पूर्णानंद संस्कृत विश्वविद्यालय से शास्त्री, वेदाचार्य एवं ज्योतिषाचार्य, संस्कृत-माध्यम शिक्षा। हिंगोली, महाराष्ट्र निवासी — षोडश संस्कार, रुद्राभिषेक, विवाह संस्कार और शांति अनुष्ठानों में समग्र वैदिक ज्ञान एवं अनुशासित शास्त्रीय साधना लाते हैं।",
  },
  {
    id: "shailendra-shukla",
    name: "Acharya Shailendra Shukla",
    tradition: "Vedic Karmakanda & Shanti Anushthan",
    traditionHi: "वैदिक कर्मकांड एवं शांति अनुष्ठान",
    place: "Uttar Pradesh",
    placeHi: "उत्तर प्रदेश",
    approach: "Scholarship · Discipline · Tradition",
    approachHi: "विद्वत्ता · अनुशासन · परंपरा",
    expertise: "Kaal Sarp Shanti · Tripindi · Pitru Dosha Nivaran",
    expertiseHi: "कालसर्प शांति · त्रिपिंडी · पितृ दोष निवारण",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Veda Parampara · Sahityacharya",
    experienceHi: "वेद परंपरा · साहित्याचार्य",
    image: "/Acharya/Shailendra Shukla.jpeg",
    qualifications: ["Veda Parampara — Vedic traditional studies", "Sahityacharya — Sanskrit literature"],
    qualificationsHi: ["वेद परंपरा — वैदिक पारंपरिक अध्ययन", "साहित्याचार्य — संस्कृत साहित्य"],
    expertiseFull: ["Karmakanda & Puja Vidhi", "Kaal Sarp Shanti Puja", "Tripindi Shradh", "Pitru Dosha Nivaran", "Mangal Shanti", "Graha Shanti & Special Anushthans", "Traditional Samskaras", "Shastric Puja Vidhi"],
    expertiseFullHi: ["कर्मकांड एवं पूजा-पाठ", "कालसर्प शांति पूजा", "त्रिपिंडी श्राद्ध", "पितृ दोष निवारण अनुष्ठान", "मंगल शांति", "ग्रह शांति एवं विशेष वैदिक अनुष्ठान", "पारंपरिक संस्कार", "शास्त्रोक्त पूजन-विधि"],
    bio: "Acharya Shailendra Shukla is an accomplished Sanskrit scholar — Veda Parampara and Sahityacharya from Sampurnanand Sanskrit University with entire Sanskrit-medium education. Rooted in Vedic tradition and Sanskrit literature, he conducts ancestral rites and Shanti ceremonies — Kaal Sarp Shanti, Tripindi Shraddha, Pitru Dosha Nivaran, Mangal and Graha Shanti — with ritual discipline and Shastric adherence.",
    bioHi:
      "आचार्य शैलेंद्र शुक्ल प्रवीण संस्कृत विद्वान हैं — सम्पूर्णानंद संस्कृत विश्वविद्यालय से वेद परंपरा एवं साहित्याचार्य, संपूर्ण संस्कृत-माध्यम शिक्षा। वैदिक परंपरा और संस्कृत साहित्य में निहित — पितृ अनुष्ठान और शांति समारोह — कालसर्प शांति, त्रिपिंडी श्राद्ध, पितृ दोष निवारण, मंगल और ग्रह शांति अनुष्ठान अनुशासन एवं शास्त्रीय पालन के साथ संपन्न कराते हैं।",
  },
  {
    id: "shivam-pandey",
    name: "Vaidik Shivam Pandey",
    tradition: "Shukla Yajurveda · Karmakanda",
    traditionHi: "शुक्ल यजुर्वेद · कर्मकांड",
    place: "Ayodhya Dham, Uttar Pradesh",
    placeHi: "अयोध्या धाम, उत्तर प्रदेश",
    approach: "Mantra · Purity · Devotion",
    approachHi: "मंत्र · शुद्धता · भक्ति",
    expertise: "Rudrabhishek · Navagraha · Japa Anushthan",
    expertiseHi: "रुद्राभिषेक · नवग्रह · जप अनुष्ठान",
    lineage: "Sampurnanand Sanskrit University · Shukla Yajurveda",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय · शुक्ल यजुर्वेद",
    experience: "Shastri · B.A. Sanskrit · Mantra Anushthan",
    experienceHi: "शास्त्री · B.A. संस्कृत · मंत्र अनुष्ठान",
    image: "/Acharya/Shivam Pandey.jpeg",
    qualifications: ["Shukla Yajurveda — Madhyandina Shakha", "Shastri — Sampurnanand Sanskrit University", "Uttar-Madhyama — Sanskrit-medium education", "B.A. Sanskrit — Saket Mahavidyalaya, Ayodhya"],
    qualificationsHi: ["शुक्ल यजुर्वेद — माध्यंदिनी शाखा", "शास्त्री — सम्पूर्णानन्द संस्कृत विश्वविद्यालय", "उत्तर-मध्यमा — संस्कृत-माध्यम शिक्षा", "B.A. संस्कृत — साकेत महाविद्यालय, अयोध्या"],
    expertiseFull: ["Shodasha Samskaras", "Karmakanda & Puja Vidhi", "Rudrabhishek & Shiva Upasana", "Yajna, Havan & Anushthans", "Vedic Japa & Mantra Anushthans", "Vivah Samskara", "Griha Pravesh & Vastu Puja", "Navagraha Puja & Shanti", "Shanti Path", "Katha, Puja & Shastric Vidhi", "Traditional Samskaras"],
    expertiseFullHi: ["षोडश संस्कार", "कर्मकांड एवं पूजा-विधि", "रुद्राभिषेक एवं शिवोपासना", "यज्ञ, हवन एवं अनुष्ठान", "वैदिक जप एवं मंत्रानुष्ठान", "विवाह संस्कार", "गृह प्रवेश एवं वास्तु पूजन", "नवग्रह पूजन एवं शांति", "शांति पाठ", "कथा, पूजन एवं शास्त्रोक्त विधियाँ", "पारंपरिक संस्कार"],
    phone: "+91 88588 10229",
    bio: "Vaidik Shivam Pandey is a traditionally trained Sanskrit scholar from Shri Dham Ayodhya — Shastri in Shukla Yajurveda (Madhyandina Shakha) with Sanskrit-medium schooling and B.A. in Sanskrit. Rooted in mantra discipline and sincere devotion, he conducts Shodasha Samskaras, Rudrabhishek and Shiva Upasana, Yajna-Havan, Japa Anushthans and Navagraha Shanti per Shastric procedure and Sanatan tradition.",
    bioHi:
      "वैदिक शिवम पाण्डेय श्रीधाम अयोध्या के परंपरागत प्रशिक्षित संस्कृत विद्वान हैं — शुक्ल यजुर्वेद (माध्यंदिनी शाखा) में शास्त्री, संस्कृत-माध्यम शिक्षा एवं B.A. संस्कृत। मंत्र अनुशासन और निष्ठापूर्ण भक्ति में निहित — षोडश संस्कार, रुद्राभिषेक एवं शिवोपासना, यज्ञ-हवन, जप अनुष्ठान और नवग्रह शांति शास्त्रोक्त विधि एवं सनातन परंपरा के अनुसार संपन्न कराते हैं। “शास्त्रोक्त विधि, वैदिक मंत्र और सनातन परंपरा — श्रद्धापूर्वक अनुष्ठान ही सेवा का आधार है। धर्मो रक्षति रक्षितः।”",
  },
  {
    id: "rahul-dwivedi",
    name: "Acharya Rahul Dwivedi",
    tradition: "Vedic Karmakanda & Shanti Anushthan",
    traditionHi: "वैदिक कर्मकांड एवं शांति अनुष्ठान",
    place: "Shri Ram Janmabhoomi, Ayodhya",
    placeHi: "श्री राम जन्मभूमि, अयोध्या",
    approach: "Scholarship · Yoga · Education",
    approachHi: "विद्वत्ता · योग · शिक्षा",
    expertise: "Kaal Sarp Shanti · Tripindi · Yoga Shastra",
    expertiseHi: "कालसर्प शांति · त्रिपिंडी · योग शास्त्र",
    lineage: "Sampurnanand Sanskrit University, Varanasi",
    lineageHi: "सम्पूर्णानंद संस्कृत विश्वविद्यालय, वाराणसी",
    experience: "Vyakaran · Sahitya · Yoga · M.A. Sanskrit",
    experienceHi: "व्याकरण · साहित्य · योग · M.A. संस्कृत",
    image: "/Acharya/Rahul Dwivedi.jpeg",
    qualifications: ["Vyakaranacharya — Sanskrit Grammar", "Sahityacharya — Sanskrit Literature", "Yogacharya — Yoga", "Shikshashastri (B.Ed.)", "M.A. in Sanskrit"],
    qualificationsHi: ["व्याकरणाचार्य — संस्कृत व्याकरण", "साहित्याचार्य — संस्कृत साहित्य", "योगाचार्य — योग", "शिक्षाशास्त्री (B.Ed.)", "एम.ए. संस्कृत"],
    expertiseFull: ["Karmakanda & Puja Vidhi", "Kaal Sarp Shanti Puja", "Tripindi Shradh", "Pitru Dosha Nivaran", "Mangal Shanti", "Graha Shanti & Special Anushthans", "Traditional Samskaras", "Shastric Puja Vidhi"],
    expertiseFullHi: ["कर्मकांड एवं पूजा-पाठ", "कालसर्प शांति पूजा", "त्रिपिंडी श्राद्ध", "पितृ दोष निवारण अनुष्ठान", "मंगल शांति", "ग्रह शांति एवं विशेष वैदिक अनुष्ठान", "पारंपरिक संस्कार", "शास्त्रोक्त पूजन-विधि"],
    bio: "Acharya Rahul Dwivedi is an accomplished Sanskrit scholar — Vyakaranacharya, Sahityacharya, Yogacharya, Shikshashastri (B.Ed.) and M.A. in Sanskrit from Sampurnanand Sanskrit University with entire Sanskrit-medium education. He brings multidisciplinary traditional scholarship to Karmakanda, Kaal Sarp Shanti, Tripindi Shraddha, Pitru Dosha Nivaran and Graha Shanti with disciplined Shastric practice.",
    bioHi:
      "आचार्य राहुल द्विवेदी प्रवीण संस्कृत विद्वान हैं — सम्पूर्णानंद संस्कृत विश्वविद्यालय से व्याकरणाचार्य, साहित्याचार्य, योगाचार्य, शिक्षाशास्त्री (B.Ed.) एवं M.A. संस्कृत, संपूर्ण संस्कृत-माध्यम शिक्षा। कर्मकांड, कालसर्प शांति, त्रिपिंडी श्राद्ध, पितृ दोष निवारण और ग्रह शांति में बहु-विषयक पारंपरिक विद्वत्ता अनुशासित शास्त्रीय साधना के साथ लाते हैं।",
  },
  {
    id: "amit-diwedy",
    name: "Acharya Amit Diwedy",
    tradition: "Numerology & Palmistry",
    traditionHi: "अंक ज्योतिष और हस्तरेखा",
    place: "Bharti Vidya Bhavan, Delhi",
    placeHi: "भारतीय विद्या भवन, दिल्ली",
    approach: "Knowledge · Discipline · Authenticity",
    approachHi: "ज्ञान · अनुशासन · प्रामाणिकता",
    expertise: "Numerology · Palmistry",
    expertiseHi: "अंकज्योतिष · हस्तरेखा",
    lineage: "Bharti Vidya Bhavan, Delhi",
    lineageHi: "भारतीय विद्या भवन, दिल्ली",
    experience: "Practising since age 40",
    experienceHi: "40 वर्ष से अभ्यास",
    image: "/amitdiwedi.jpg",
    qualifications: ["Gold Medal — Civil Engineering, Bharti Vidyapeeth Pune", "MBA — Construction Management", "Numerology & Palmistry — Bharti Vidya Bhavan, Delhi"],
    qualificationsHi: ["स्वर्ण पदक — सिविल इंजीनियरिंग, भारती विद्यापीठ पुणे", "MBA — निर्माण प्रबंधन", "अंकज्योतिष एवं हस्तरेखा — भारतीय विद्या भवन, दिल्ली"],
    expertiseFull: ["Numerology", "Palmistry", "Positive guidance"],
    expertiseFullHi: ["अंकज्योतिष", "हस्तरेखा", "सकारात्मक मार्गदर्शन"],
    phone: "+91 99587 28666",
    email: "macparmarth@gmail.com",
    bio: "Amit is a Civil Engineering Graduate with Gold Medal from Bharti Vidyapeeth, Pune. After graduation, he did his MBA in Construction Management. He runs a business which is into Interior Designing. He enjoys playing Cricket and plays for his Cricket Club in Delhi. Additionally, he is a Trustee with Nursing Tree Trust which aims at the betterment of society & his alumni. Amit had an inclination towards Palmistry since he was in Class 10th but studies & life kept him busy. At the age of 40, he took this hobby as a profession and is now a known Numerologist and a Palmist after Graduating from Bharti Vidya Bhavan, Delhi. Amit wants to retire at the age of 45 and take this Journey to new heights where he can give to the society by doing a Positive Palmistry and Numerology aiming at the welfare of the society.",
    bioHi:
      "अमित भारती विद्यापीठ, पुणे से स्वर्ण पदक विजेता सिविल इंजीनियरिंग स्नातक हैं। स्नातक के बाद उन्होंने निर्माण प्रबंधन में एमबीए किया। वे इंटीरियर डिज़ाइनिंग का व्यवसाय चलाते हैं। वे क्रिकेट खेलना पसंद करते हैं और दिल्ली में अपने क्रिकेट क्लब के लिए खेलते हैं। साथ ही, वे नर्सिंग ट्री ट्रस्ट के ट्रस्टी हैं जो समाज और उनके एलुमनाई के उत्थान का लक्ष्य रखता है। अमित की कक्षा 10वीं से ही हस्तरेखा के प्रति रुचि थी, पर अध्ययन और जीवन व्यस्त रखते थे। 40 वर्ष की आयु में उन्होंने इस शौक को व्यवसाय बनाया और भारतीय विद्या भवन, दिल्ली से स्नातक के बाद अब वे एक जाने-माने अंक ज्योतिषी और हस्तरेखा विशेषज्ञ हैं। अमित 45 वर्ष की आयु में सेवानिवृत्त होकर इस यात्रा को नई ऊँचाइयों पर ले जाना चाहते हैं जहाँ वे सकारात्मक हस्तरेखा और अंकज्योतिष के माध्यम से समाज के कल्याण में योगदान दे सकें।",
  },
  {
    id: "mohit-sharma",
    name: "Acharya Mohit Sharma",
    tradition: "Vedic Astrology & Palmistry",
    traditionHi: "वैदिक ज्योतिष और हस्तरेखा",
    place: "Jyotish Acharya · Delhi",
    placeHi: "ज्योतिष आचार्य · दिल्ली",
    approach: "Knowledge · Discipline · Authenticity",
    approachHi: "ज्ञान · अनुशासन · प्रामाणिकता",
    expertise: "Jyotish · Palmistry · Numerology",
    expertiseHi: "ज्योतिष · हस्तरेखा · अंकज्योतिष",
    lineage: "Jyotish Alankar · Jyotish Acharya",
    lineageHi: "ज्योतिष अलंकार · ज्योतिष आचार्य",
    experience: "10+ years",
    experienceHi: "10+ वर्ष",
    image: "/mohitsharma.jpg",
    qualifications: ["Jyotish Alankar", "Jyotish Acharya", "Diploma — Palmistry & Numerology"],
    qualificationsHi: ["ज्योतिष अलंकार", "ज्योतिष आचार्य", "डिप्लोमा — हस्तरेखा एवं अंकज्योतिष"],
    expertiseFull: ["Jyotish", "Palmistry", "Numerology"],
    expertiseFullHi: ["ज्योतिष", "हस्तरेखा", "अंकज्योतिष"],
    phone: "+91 98682 38906",
    email: "macparmarth@gmail.com",
    bio: "Mohit Sharma, a Final Year Student in CA and CS, discovered his passion for Astrology while working in Finance for Corporates. What started as a hobby evolved into a deep interest, where he dived deeper into the Ancient Occult Science of Astrology. Alongside Astrology, he is also an avid cricketer. With over a decade of experience, he holds degrees in Jyotish Alankar, Jyotish Acharya, and has completed Diploma in Palmistry and Numerology. As a trusted astrologer, Mohit aims to use his knowledge for human welfare, blending traditional and modern techniques, which has garnered him a global following as a consultant and teacher.",
    bioHi:
      "मोहित शर्मा, सीए और सीएस के अंतिम वर्ष के छात्र, ने कॉर्पोरेट्स के लिए वित्त में कार्य करते हुए ज्योतिष के प्रति अपना जुनून खोजा। जो शौक से शुरू हुआ, वह एक गहरी रुचि में बदल गया, जहाँ उन्होंने ज्योतिष के प्राचीन गूढ़ विज्ञान में गहराई से उतरा। ज्योतिष के साथ-साथ, वे क्रिकेट के भी शौकीन हैं। एक दशक से अधिक के अनुभव के साथ, उन्होंने ज्योतिष अलंकार, ज्योतिष आचार्य में डिग्री हासिल की है, और हस्तरेखा एवं अंकज्योतिष में डिप्लोमा पूरा किया है। एक भरोसेमंद ज्योतिषी के रूप में, मोहित का लक्ष्य अपने ज्ञान का उपयोग मानव कल्याण के लिए करना है, पारंपरिक और आधुनिक तकनीकों को मिलाकर, जिसने उन्हें एक सलाहकार और शिक्षक के रूप में वैश्विक अनुसरण दिलाया है।",
  },
  {
    id: "chandra-shekhar-samavedula",
    name: "Acharya Chandra Shekhar Samavedula",
    tradition: "Graphology · Numerology · Astrology",
    traditionHi: "ग्राफोलॉजी · अंकज्योतिष · ज्योतिष",
    place: "Delhi-NCR",
    placeHi: "दिल्ली-एनसीआर",
    approach: "Knowledge · Discipline · Authenticity",
    approachHi: "ज्ञान · अनुशासन · प्रामाणिकता",
    expertise: "Graphology · Numerology · Astrology · Wristwatch Analysis",
    expertiseHi: "ग्राफोलॉजी · अंकज्योतिष · ज्योतिष · कलाई घड़ी विश्लेषण",
    lineage: "3+ years of practice",
    lineageHi: "3+ वर्ष का अभ्यास",
    experience: "3+ years",
    experienceHi: "3+ वर्ष",
    image: "/chandrashekhar.jpg",
    qualifications: ["Graphology", "Numerology", "Astrology & Wristwatch Analysis"],
    qualificationsHi: ["ग्राफोलॉजी", "अंकज्योतिष", "ज्योतिष एवं कलाई घड़ी विश्लेषण"],
    expertiseFull: ["Graphology", "Numerology", "Astrology"],
    expertiseFullHi: ["ग्राफोलॉजी", "अंकज्योतिष", "ज्योतिष"],
    phone: "+91 99582 53666",
    email: "macparmarth@gmail.com",
    bio: "An IT professional with 27 years of Industry experience, working with European MNC in Delhi-NCR. A Numismatist with a vast Collection of coins, Chandra enjoys hiking in Aravalis on weekends. Entered in the world of Occult Sciences with the aim to spread positivity in the society and bust the myths around various misconception. Chandra learnt different sciences for the betterment of the society. He has been working in this area for over 3 years & helped many adolescent school going children to overcome their fear just by analyzing the simplest drawing and providing the simple therapies and remedies. At the same time, Chandra has guided the people from different walks of life by providing the consultancy through Numerology, Hand-writing and Signature analysis and necessary changes, also advising the right kind of Wrist Watch to improve their married lives.",
    bioHi:
      "दिल्ली-एनसीआर में एक यूरोपीय बहुराष्ट्रीय कंपनी के साथ कार्यरत 27 वर्ष के उद्योग अनुभव वाले आईटी पेशेवर। विशाल सिक्का संग्रह वाले एक मुद्राशास्त्री, चंद्रा सप्ताहांत में अरावली में हाइकिंग का आनंद लेते हैं। समाज में सकारात्मकता फैलाने और विभिन्न भ्रांतियों के इर्द-गिर्द के मिथकों को दूर करने के उद्देश्य से गूढ़ विज्ञान की दुनिया में प्रवेश किया। चंद्रा ने समाज के उत्थान के लिए विभिन्न विज्ञान सीखे। वे इस क्षेत्र में 3 वर्ष से अधिक से कार्यरत हैं और केवल सरल चित्रकला का विश्लेषण करके और सरल चिकित्सा एवं उपाय प्रदान करके कई किशोर विद्यालय जाने वाले बच्चों के भय को दूर करने में सहायता की है। साथ ही, चंद्रा ने अंकज्योतिष, हस्तलेख और हस्ताक्षर विश्लेषण और आवश्यक परिवर्तनों के माध्यम से विभिन्न क्षेत्रों के लोगों को परामर्श दिया है, और उनके वैवाहिक जीवन में सुधार के लिए सही प्रकार की कलाई घड़ी की सलाह भी दी है।",
  },
];
